<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Privacy Policy | TravelTourism</title><meta name="description" content="How TravelTourism collects, uses, stores and protects personal information."><link rel="stylesheet" href="${pageContext.request.contextPath}/css/style.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/css/legal-pages.css?v=1"></head><body><%@ include file="common/header.jsp" %>
<main class="legal-page"><header class="legal-hero"><p>PRIVACY AT TRAVELTOURISM</p><h1>Your information,<br><em>handled with care.</em></h1><div><span>Effective 5 September 2026</span><span>Applies to website visitors and guests</span></div></header>
<div class="legal-layout"><aside><p>ON THIS PAGE</p><nav><a href="#scope">01 · Scope</a><a href="#collect">02 · Information we collect</a><a href="#use">03 · How we use it</a><a href="#sharing">04 · Sharing</a><a href="#retention">05 · Retention &amp; security</a><a href="#choices">06 · Your choices</a><a href="#contact">07 · Contact us</a></nav><div><strong>Plain-language promise</strong><p>We use the details you give us to operate the website, respond to enquiries and process travel requests.</p></div></aside>
<article><section class="legal-opening"><p>This Privacy Policy explains how TravelTourism collects and handles personal information when you browse this website, send an enquiry, request a booking, or otherwise contact us.</p><p>By using the website, you acknowledge the practices described here. Where consent is required, we will ask for it through an appropriate notice or action.</p></section>
<section id="scope"><span>01</span><h2>Scope of this policy</h2><p>This policy applies to information collected through the TravelTourism website and the forms available on it. It does not govern a third-party website, payment service, hotel, carrier, activity provider, map, or social platform that has its own privacy practices.</p></section>
<section id="collect"><span>02</span><h2>Information we collect</h2><h3>Information you provide</h3><ul><li>Identity and contact details, including your name, email address and phone number.</li><li>Travel information such as destination, travel month or date, number of travellers, budget, preferences, occasion and accessibility or dietary requests you choose to share.</li><li>Enquiry messages, booking requests, package selections, and later correspondence with our team.</li><li>Administrative records created while responding to an enquiry, such as its status, follow-up date and internal service notes.</li></ul><h3>Information created through website use</h3><p>Our server may process basic technical information needed to deliver and protect the website, such as request time, requested page, browser information, IP address and error logs. We do not ask you to provide payment-card information through the contact or booking-request forms.</p><p>Please avoid including passports, government identification numbers, financial credentials, medical records or other highly sensitive information in a general enquiry unless our team specifically requests it through an appropriate channel.</p></section>
<section id="use"><span>03</span><h2>How we use information</h2><ul><li>To answer questions and understand the journey you want to plan.</li><li>To review booking requests, check availability, calculate or confirm package details, and contact you about next steps.</li><li>To maintain an enquiry workflow, record follow-ups, provide customer support and preserve service history.</li><li>To operate, troubleshoot, secure and improve the website and its forms.</li><li>To prevent misuse and meet applicable legal, accounting or regulatory requirements.</li></ul><p>We do not state that an enquiry is a confirmed reservation. Information submitted through a form is used to review and respond to the request.</p></section>
<section id="sharing"><span>04</span><h2>When information may be shared</h2><p>We may share the minimum information reasonably needed with hotels, transport providers, guides, activity operators, technology providers or other travel suppliers when it is necessary to prepare, confirm or deliver a service you request. We may also disclose information when required by law, to protect users or the website, or in connection with a legitimate business reorganisation.</p><p>We do not sell personal information submitted through our enquiry or booking forms.</p></section>
<section id="retention"><span>05</span><h2>Retention and security</h2><p>We retain information for as long as reasonably needed to answer the request, provide the service, maintain necessary transaction and support records, resolve disputes, prevent fraud and meet legal obligations. Retention periods can differ according to the nature of the enquiry or booking.</p><p>We use reasonable administrative and technical safeguards designed to protect stored information. No internet transmission or storage system can be guaranteed completely secure, so please use care when deciding what to submit online.</p></section>
<section id="choices"><span>06</span><h2>Your choices and requests</h2><p>Subject to applicable law, you may ask us to explain the personal information we hold about you, correct inaccurate information, erase information that is no longer required, or withdraw consent where processing depends on consent. Some information may need to be retained for legal, security, fraud-prevention or transaction-record purposes.</p><p>Include enough detail for us to identify the relevant enquiry or booking. We may take reasonable steps to verify that a request comes from the correct person.</p></section>
<section><span>07</span><h2>Children, updates and external links</h2><p>This website is intended for adults arranging travel. A parent or lawful guardian should submit information required to plan travel for a child. We may update this policy when our services or legal obligations change. The effective date at the top shows the latest published version.</p></section>
<section id="contact" class="legal-contact"><p>PRIVACY QUESTIONS</p><h2>Talk to us about your information.</h2><p>Email <a href="mailto:info@traveltourism.com">info@traveltourism.com</a> or use our contact form. You may also write to TravelTourism, Mumbai, Maharashtra, India.</p><a class="legal-button" href="${pageContext.request.contextPath}/contact">Contact TravelTourism →</a></section>
</article></div></main><%@ include file="common/footer.jsp" %></body></html>